apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/sigma-rarity-378302/my-docker-repo/container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: pv-storage
              mountPath: /Fenil_PV_dir  
        - name: container2
          image: us-central1-docker.pkg.dev/sigma-rarity-378302/my-docker-repo/container2:latest
          ports:
            - containerPort: 6002
          volumeMounts:
            - name: pv-storage
              mountPath: /Fenil_PV_dir
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: my-app-pvc          

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      name: c1-port
    - protocol: TCP
      port: 6002
      targetPort: 6002
      name: c2-port